import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { cn } from "@/lib/utils";
import { Sidebar } from "@/components/Sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("flex min-h-screen flex-col", inter.className)}>
        <Providers>
          <div className="flex">
            <Sidebar />
            <div className="mx-auto md:w-10/12 p-2 md:p-8">{children}</div>
          </div>
        </Providers>
      </body>
    </html>
  );
}
